language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install --dev --prefer-source
  - php -S localhost:1000 testapi/index.php &
  - sleep 3

script:
  - vendor/bin/phpcs --standard=psr2 src
  - vendor/bin/phpspec r
  - vendor/bin/behat

matrix:
    fast_finish: true
    allow_failures:
        - php: 7
