language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install --dev --prefer-source
  - php -S localhost:1080 testapi/index.php &
  - sleep 3

script:
  - composer test

branches:
  only:
    - master
    - develop

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: 7
